[package]
name = "common"
version = "0.1.0"
authors = ["Dylan"]
edition = "2018"

[dependencies]
rand = "0.6.1"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.5"

[lib]
crate-type = ["cdylib", "rlib"]